/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const debug: typeof import('src/utils/debug')['debug']
  const debugError: typeof import('@/utils/debug')['debugError']
  const debugLog: typeof import('@/utils/debug')['debugLog']
  const debugWarn: typeof import('@/utils/debug')['debugWarn']
}
